# Generated by Django 3.1 on 2020-11-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0003_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
